# Lead Scraper Configuration
scraping:
  # Skip email fetching for projects with first commit before this date
  # Format: YYYY-MM-DD or YYYY (defaults to January 1st)
  min_first_commit_date: "2015"
  
  # Skip email fetching for repositories created before this date
  min_repository_created_date: "2015"
  
  # Rate limiting between API calls (milliseconds)
  rate_limit_delay_ms: 100
  
  # Timeout for individual API calls (seconds)
  api_timeout_seconds: 10
  
  # Maximum number of projects to process per source (0 = unlimited)
  max_projects_per_source: 0

logging:
  # Log level: trace, debug, info, warn, error
  level: "info"
  
  # Show progress every N projects
  progress_interval: 10

output:
  # Output directory for JSON files
  directory: "out"
  
  # Pretty print JSON files
  pretty_json: true


email_limits:
  # Daily limits for different account ages (days since first email sent)
  new_account: 300       # First 7 days
  warming_up: 300       # Days 8-30
  established: 500       # Days 31-90
  mature: 1000          # 90+ days
  
  # Rate limiting
  emails_per_hour: 400
  emails_per_minute: 300
  delay_between_emails_ms: 3000  # 3 seconds minimum
  
  # Ramp up settings
  enable_auto_ramp: true
  ramp_percentage_increase: 30   # Increase limit by 20% each week
  max_ramp_daily_limit: 300
  
  # Safety settings
  max_emails_per_campaign: 400   # Hard limit per campaign run
  require_confirmation_above: 50 # Ask for confirmation if sending more than 50
  
  # Warm-up mode for new domains
  warm_up_mode: true
  warm_up_daily_limits: [20, 30, 50, 100, 200]  # Day 1, 2, 3, 4, 5...
