# config.yml - Add web crawler configuration
# Lead Scraper Configuration
scraping:
  min_first_commit_date: "2015"
  min_repository_created_date: "2015"
  rate_limit_delay_ms: 100
  api_timeout_seconds: 10
  max_projects_per_source: 0

logging:
  level: "info"
  progress_interval: 10

output:
  directory: "out"
  pretty_json: true

email_limits:
  new_account: 400
  established: 500
  mature: 1000
  emails_per_hour: 400
  emails_per_minute: 400
  delay_between_emails_ms: 3000
  enable_auto_ramp: true
  ramp_percentage_increase: 30
  max_ramp_daily_limit: 400
  max_emails_per_campaign: 400
  require_confirmation_above: 50

# NEW: Web crawler configuration
web_crawler:
  # Default crawl settings
  default_max_pages: 3
  default_delay_ms: 2000
  default_timeout_seconds: 60
  
  # Respectful crawling
  respect_robots_txt: true
  user_agent: "Mozilla/5.0 (compatible; ContactCrawler/1.0; +https://fabinvest.com)"
  
  # Contact extraction settings
  min_confidence_threshold: 0.5
  max_contacts_per_site: 10
  
  # Output settings
  save_full_html: false
  save_crawl_logs: true
